### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by Zumbalamambo** [ManifoldFR/recvis-project#2]
Please share the pretrained model

**Comment by ManifoldFR** [comment]
Hi

We have no pretrained models of ours, we only use the pretrained models from the initial HMR, motion_reconstruction and AlphaPose repositories

**Comment by Zumbalamambo** [comment]
I'm getting the following error, :(

`

> ModuleNotFoundError: No module named 'opendr'


`

**Comment by ManifoldFR** [comment]
You'll have to install `opendr` via pip, but be careful recent versions of pip might be broken with it. [See this thread and answer](https://github.com/akanazawa/hmr/issues/82#issuecomment-557430371)
